# Site
name: 'Just A Word'
description: 'A blog by Flawnson'
logo: 'assets/images/just-a-word-icon-small.jpg'
favicon: 'assets/images/just_a_word_icon.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'flawnsontong1@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme

remote_theme: https://github.com/wowthemesnet/mundana-theme-jekyll
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: flawnson

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 5

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
